ALTER TABLE jobs ADD COLUMN IF NOT EXISTS status VARCHAR(30) DEFAULT 'published';
CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,email VARCHAR(320) UNIQUE NOT NULL,password_hash VARCHAR(500) NOT NULL,full_name VARCHAR(160) NOT NULL,role VARCHAR(30) DEFAULT 'candidate',active BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS profiles(user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,location VARCHAR(160),highest_qualification VARCHAR(220),graduation_year INTEGER,skills TEXT,preferred_roles TEXT,preferred_locations TEXT,date_of_birth DATE);
CREATE TABLE IF NOT EXISTS saved_jobs(
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    job_id INTEGER NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    CONSTRAINT uq_saved_user_job UNIQUE(user_id, job_id)
);

CREATE INDEX IF NOT EXISTS ix_saved_jobs_user_id
ON saved_jobs(user_id);

CREATE INDEX IF NOT EXISTS ix_saved_jobs_job_id
ON saved_jobs(job_id);
CREATE TABLE IF NOT EXISTS applications(id SERIAL PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,job_id INTEGER REFERENCES jobs(id) ON DELETE SET NULL,company VARCHAR(220) NOT NULL,role VARCHAR(220) NOT NULL,status VARCHAR(50) DEFAULT 'planned',applied_on DATE,next_deadline DATE,notes TEXT);
CREATE TABLE IF NOT EXISTS organizations(id SERIAL PRIMARY KEY,name VARCHAR(220) UNIQUE NOT NULL,website VARCHAR(1000),verified BOOLEAN DEFAULT FALSE);
CREATE TABLE IF NOT EXISTS alerts(id SERIAL PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,alert_type VARCHAR(50) NOT NULL,query TEXT,enabled BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS audit_logs(id SERIAL PRIMARY KEY,action VARCHAR(120) NOT NULL,entity_type VARCHAR(80) NOT NULL,entity_id VARCHAR(120),detail TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
